### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jayfk** [djangopackages/djangopackages#460]
Djangopackages.org is currently in deep hibernation. It works and remains very useful for the Django community, but needs a lot of work to be maintainable in the long run.

## Roadmap
- [x] Deprecate/remove unwanted views and features https://github.com/pydanny/djangopackages/issues/459
- [x] Evaluate if dependencies are maintained/supporting Python 3 and Django 1.11 https://github.com/pydanny/djangopackages/issues/457
- [x] Port djangopackages to Python 3 https://github.com/pydanny/djangopackages/issues/379
- [x] Update to Django 1.11 https://github.com/pydanny/djangopackages/issues/458
